/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Models.Repartidor;
import Models.Response;
import Requests.Requester;
import java.awt.Color;
import java.io.IOException;
import java.net.ProtocolException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import org.apache.http.client.ClientProtocolException;
import org.json.JSONException;

/**
 *
 * @author DiegoAlvarez
 */
public class AddDealer extends javax.swing.JFrame {
    boolean show;
    /**
     * Creates new form AddDealer
     */
    public AddDealer() {
        initComponents();
        show = true;
        passField.setEchoChar('●');
        confirmPassField.setEchoChar('●');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        placaField = new javax.swing.JTextField();
        PlacaLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        PlacaLabel1 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        showPass = new javax.swing.JToggleButton();
        PlacaLabel3 = new javax.swing.JLabel();
        confirmPassField = new javax.swing.JPasswordField();
        saveButton = new javax.swing.JToggleButton();
        mensajeName = new javax.swing.JLabel();
        mensajeCelular = new javax.swing.JLabel();
        mensajePlaca = new javax.swing.JLabel();
        mensajeEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 350));
        setPreferredSize(new java.awt.Dimension(1000, 350));

        placaField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        placaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaFieldActionPerformed(evt);
            }
        });
        placaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placaFieldKeyTyped(evt);
            }
        });

        PlacaLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlacaLabel2.setText("Placa:");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel.setText("Nombre:");

        nameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        phoneNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNumberLabel.setText("Celular:");

        phoneField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneFieldKeyTyped(evt);
            }
        });

        EmailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmailLabel.setText("Email:");

        PlacaLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlacaLabel1.setText("Password:");

        emailField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailFieldKeyTyped(evt);
            }
        });

        passField.setToolTipText("");
        passField.setPreferredSize(new java.awt.Dimension(6, 23));
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });

        showPass.setIcon(new javax.swing.ImageIcon("C:\\Users\\DiegoAlvarez\\Documents\\GitHub\\Quickware\\QuickwareApp\\src\\main\\java\\UI\\resources\\on.png")); // NOI18N
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });

        PlacaLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlacaLabel3.setText("Confirmar:");

        confirmPassField.setToolTipText("");
        confirmPassField.setPreferredSize(new java.awt.Dimension(6, 23));
        confirmPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassFieldActionPerformed(evt);
            }
        });

        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        mensajeName.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        mensajeName.setForeground(new java.awt.Color(153, 0, 0));

        mensajeCelular.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        mensajeCelular.setForeground(new java.awt.Color(153, 0, 0));

        mensajePlaca.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        mensajePlaca.setForeground(new java.awt.Color(153, 0, 0));

        mensajeEmail.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        mensajeEmail.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(mensajeName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(mensajeCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(mensajeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PlacaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PlacaLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PlacaLabel3)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(placaField, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmPassField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(showPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensajePlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nameLabel))
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(placaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showPass, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PlacaLabel1)
                                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmPassField, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(PlacaLabel3))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlacaLabel2)
                            .addComponent(mensajePlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        show = !show;
        if(show){
            passField.setEchoChar((char)0);
            confirmPassField.setEchoChar((char)0);
            showPass.setIcon(new javax.swing.ImageIcon("C:\\Users\\DiegoAlvarez\\Documents\\GitHub\\Quickware\\QuickwareApp\\src\\main\\java\\UI\\resources\\off.png"));
        }
        else{
            passField.setEchoChar('●');
            confirmPassField.setEchoChar('●');
            showPass.setIcon(new javax.swing.ImageIcon("C:\\Users\\DiegoAlvarez\\Documents\\GitHub\\Quickware\\QuickwareApp\\src\\main\\java\\UI\\resources\\on.png"));
        }
    }//GEN-LAST:event_showPassActionPerformed
    private boolean getValidation(String name, String phoneNumber, String email, String placa, String password, String passwordConf){
        boolean eRigth = true;
        boolean rightName = Pattern.matches("^[a-zA-Z\\u00f1\\u00d1]{1,30}( [a-zA-Z\\u00f1\\u00d1]{1,30}){1,3}$", name);
        boolean rightNumber = Pattern.matches("^\\d{4}-? ?\\d{4}$", phoneNumber);
        boolean rightEmail = Pattern.matches("^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$", email);
        boolean rightPlaca = Pattern.matches("^((([a-zA-Z\\u00f1\\u00d1]{3})|\\d{3})-?\\d{3})|\\d{4,5}$", placa);
        boolean rightPass = Pattern.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$", password);
        System.out.println(password);
        if (!rightName){
            mensajeName.setText("<html>Minimo un nombre y un apellido.<br/>No usar caracteres especiales o numeros.</html>");
            nameField.setForeground(new Color(153,0,0));
            
        }
        if(!rightNumber){
            mensajeCelular.setText("<html>Los formatos de celular validos son:<br/>1234-5678 o 12345678</html>");
            phoneField.setForeground(new Color(153,0,0));
            eRigth = false;
        }
        if(!rightEmail){
            mensajeEmail.setText("<html>Formato de email invalido:<br/>Ejemplo: correo@operador.dominio</html>");
            emailField.setForeground(new Color(153,0,0));
            eRigth = false;
        }
        if(!rightPlaca){
            mensajePlaca.setText("<html>Formato de email invalido:<br/>Ejemplo: correo@operador.dominio</html>");
            placaField.setForeground(new Color(153,0,0));
            eRigth = false;
        }
        if(!password.equals(passwordConf)){
            JOptionPane.showMessageDialog(null,"La contraseñas no coinciden", "Error de contraseña.", JOptionPane.ERROR_MESSAGE);
            eRigth = false;
        }
        if(!rightPass){
            JOptionPane.showMessageDialog(null,"<html>Formato Incorrecto.<br/>-Minimo 8 caracteres.<br/>-Minimo una mayuscula, una minuscula y un numero.</html>", "Error de contraseña.", JOptionPane.ERROR_MESSAGE);
            eRigth = false;
        }
        return eRigth;
    }
    private void controlResponse(Response resp) throws IOException, ProtocolException{
        if(resp.code == 0){
            JOptionPane.showMessageDialog(null,"El repartidor ha sido añadido con éxito", "Éxito.", JOptionPane.INFORMATION_MESSAGE);
            try {
                new MainMenu().setVisible(true);
                this.setVisible(false);
            } catch (JSONException ex) {
                Logger.getLogger(AddDealer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,resp.message, "Error al insertar repartidor.", JOptionPane.ERROR_MESSAGE);
        }

    }
    private void createObject() throws ClientProtocolException, JSONException, JSONException{
        String name = nameField.getText();
        String phoneNumber = phoneField.getText();
        String email = emailField.getText();
        String placa = placaField.getText();
        String password = String.valueOf(passField.getPassword());
        String passwordConf =String.valueOf(confirmPassField.getPassword());
         
        if (getValidation(name, phoneNumber, email, placa,password,passwordConf)){
            Repartidor nuevoRep = new Repartidor(name,email,placa,phoneNumber,password);
            Requester reqs = new Requester();
            try {
                controlResponse(reqs.registerRepartidor(nuevoRep));
            } catch (IOException ex) {
                Logger.getLogger(AddDealer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void confirmPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            saveButton.setVisible(false);
            Requester reqs = new Requester();
            createObject();
            saveButton.setVisible(true);
        } catch (ClientProtocolException ex) {
            Logger.getLogger(AddDealer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(AddDealer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained

    }//GEN-LAST:event_nameFieldFocusGained

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        mensajeName.setText("");
        nameField.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_nameFieldKeyTyped

    private void emailFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyTyped
        mensajeEmail.setText("");
        emailField.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_emailFieldKeyTyped

    private void phoneFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyTyped
        mensajeCelular.setText("");
        phoneField.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_phoneFieldKeyTyped

    private void placaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placaFieldKeyTyped
        mensajePlaca.setText("");
        placaField.setForeground(new Color(0,0,0));    }//GEN-LAST:event_placaFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDealer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel PlacaLabel1;
    private javax.swing.JLabel PlacaLabel2;
    private javax.swing.JLabel PlacaLabel3;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel mensajeCelular;
    private javax.swing.JLabel mensajeEmail;
    private javax.swing.JLabel mensajeName;
    private javax.swing.JLabel mensajePlaca;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField placaField;
    private javax.swing.JToggleButton saveButton;
    private javax.swing.JToggleButton showPass;
    // End of variables declaration//GEN-END:variables
}
